blank_issues_enabled: false
contact_links:
    - name: Bug reports
      url: https://github.com/ente-io/ente/issues/new/choose
      about: Open issues in ente-io/ente
    - name: Feature requests and questions
      url: https://github.com/ente-io/ente/discussions
      about: Open feature requests in ente-io/ente
